language: node_js
node_js:
  - "node"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - npm run lint
  - npm run build
cache:
  nvm: trues
  yarn: true
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key:
    secure: "a628fa20-a233-4b74-bdc1-37aa4f5e7236"
  on:
    all_branches: true
